### ISSUE TITLE
Check security issue with hoek dependency

### ISSUE THREAD

**Issue by tgeci** [dodevops/socko#1]
We should check all the node based repos about the hoek dependency and update them. There is a dangerous security issue. 

Github is also warning about it:
![hoek](https://user-images.githubusercontent.com/4592657/40102532-0adb1770-58eb-11e8-9e61-946c473df86d.png)

**Comment by dploeger** [comment]
I also checked that, but the hoek-vulnerability seems to come from tsdoc, which is only used for dev purposes. But perhaps we could specifically set the fixed version of hoek in all package.jsons

**Comment by dploeger** [comment]
I'm sorry, but we're archiving the Socko project because it isn't maintained anymore and the usage for it somehow outlived itself.
